#!/usr/bin/env node
// Generates `as const` TS ABIs in ./abi from forge build artifacts. Run via
// `npm run generate-abis`. Add a robot by appending to ABIS.

import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname, resolve, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const OUT_DIR = resolve(REPO_ROOT, 'out');
const ABI_DIR = resolve(HERE, 'abi');

const ABIS = [{name: 'IAaveCREReceiver'}, {name: 'IHub'}];

function runForgeBuild() {
  console.log('▸ forge build');
  const r = spawnSync('forge', ['build'], {stdio: 'inherit', cwd: REPO_ROOT});
  if (r.status !== 0) {
    console.error('forge build failed');
    process.exit(r.status ?? 1);
  }
}

async function emitOne({name}) {
  const artifactPath = resolve(OUT_DIR, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    console.error(`✗ missing artifact for ${name} at ${relative(REPO_ROOT, artifactPath)}`);
    process.exit(1);
  }
  const artifact = JSON.parse(await readFile(artifactPath, 'utf8'));
  const tsPath = resolve(ABI_DIR, `${name}.ts`);
  const header = [
    '// AUTOGENERATED — DO NOT EDIT. Run `npm run generate-abis` to refresh.',
    '',
    `export const ${name}ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    '',
  ].join('\n');
  await writeFile(tsPath, header);
  console.log(`✓ ${relative(REPO_ROOT, tsPath)}`);
}

async function main() {
  runForgeBuild();
  await mkdir(ABI_DIR, {recursive: true});
  for (const entry of ABIS) await emitOne(entry);
}

await main();
